### ISSUE TITLE
lucas-clemente/quic-go throw error when compile

### ISSUE THREAD

**Issue by williampgdv** [micro/micro#320]
When compile with golang 1.13. The following package problem occur. Seem the 0.12 version is not compatible with gaoling 1.13.

github.com/lucas-clemente/quic-go/internal/handshake
/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.12.0/internal/handshake/crypto_setup.go:501:72: undefined: qtls.CipherSuite
/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.12.0/internal/handshake/crypto_setup.go:523:73: undefined: qtls.CipherSuite

**Comment by tiancityycf** [comment]
同样遇到问题 。。。  求解决方案。。。  好像是环境问题

**Comment by asim** [comment]
Are you using go mod?

**Comment by williampgdv** [comment]
> Are you using go mod?

Yes. 

I solve this by replace the lucas-clemente/quic-go to last commit and it solve the problem.

replace github.com/lucas-clemente/quic-go => github.com/lucas-clemente/quic-go v0.7.1-0.20190913061013-f15a82d3fdc3

**Comment by vtolstov** [comment]
Go-micro must be pinned to 0.12.0 of quic-go.

**Comment by vtolstov** [comment]
@williampgdv strange commit version string.... i'm pin to v0.12.0 inside my app go.mod and all works fine. May be some other have dep that needs version above, so go-micro pinning overriden.

**Comment by williampgdv** [comment]
@vtolstov 

i use go **get github.com/lucas-clemente/quic-go@master** to get this version string. It should point to latest commit.

**Comment by asim** [comment]
Please use go modules and go version 1.13. When you `go get github.com/micro/micro` this should work.
